// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadAndCalc.Models;

namespace UploadAndCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200213232225_SetupDB")]
    partial class SetupDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UploadAndCalc.Models.CalcItem", b =>
                {
                    b.Property<int>("CalcItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CalcItemValue")
                        .HasColumnType("float");

                    b.HasKey("CalcItemId");

                    b.ToTable("CalcItems");
                });
#pragma warning restore 612, 618
        }
    }
}
